"""The test harness itself: the right database, isolation, and deterministic factories."""

import pytest
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession

from app.core.settings import TEST_DATABASE_NAME
from tests.factories import SEED
from tests.support.models import Widget, WidgetFactory

pytestmark = pytest.mark.anyio


async def test_tests_run_against_the_test_database(session: AsyncSession) -> None:
    assert await session.scalar(text("SELECT current_database()")) == TEST_DATABASE_NAME


async def test_test_database_is_migrated(session: AsyncSession) -> None:
    assert await session.scalar(text("SELECT to_regclass('alembic_version')")) is not None


@pytest.mark.usefixtures("support_tables")
async def test_committed_test_data_is_invisible_to_other_connections(
    session: AsyncSession, engine: AsyncEngine
) -> None:
    session.add(Widget(name="private"))
    await session.commit()  # releases a savepoint; the outer transaction is still open

    async with engine.connect() as other:
        visible = await other.scalar(text("SELECT to_regclass('support_widget')"))

    assert visible is None  # even the table exists only inside this test's transaction


@pytest.mark.usefixtures("support_tables")
async def test_factory_persists_through_the_test_session(session: AsyncSession) -> None:
    widget = await WidgetFactory.create_async()

    assert await session.scalar(select(Widget.name).where(Widget.id == widget.id)) == widget.name
    assert widget.id.version == 7  # left to the model, not generated by the factory
    assert widget.created_at is not None  # left to the database


def test_factory_values_are_reproducible_from_the_seed() -> None:
    WidgetFactory.seed_random(SEED)
    first = [WidgetFactory.build().name for _ in range(3)]
    WidgetFactory.seed_random(SEED)
    second = [WidgetFactory.build().name for _ in range(3)]

    assert first == second


def test_factory_values_given_explicitly_win() -> None:
    assert WidgetFactory.build(name="chosen", quantity=3).quantity == 3
