"""add foreign key lookup indexes

Revision ID: 950169fd7ea9
Revises: de363d1a3629
Create Date: 2026-10-09 08:52:28.630265

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "950169fd7ea9"
down_revision: str | Sequence[str] | None = "de363d1a3629"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_membership_organization_id"), "membership", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_organization_id"), "project", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_session_user_id"), "session", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_user_id"), table_name="session")
    op.drop_index(op.f("ix_project_organization_id"), table_name="project")
    op.drop_index(op.f("ix_membership_organization_id"), table_name="membership")
    # ### end Alembic commands ###
